name: build-and-test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

env:
  CC: /usr/lib/ccache/gcc
  CXX: /usr/lib/ccache/g++

jobs:
  build-and-test:
    runs-on: [self-hosted, linux, X64]
    container: ${{ matrix.container }}${{ matrix.container-suffix }}
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - humble
        container-suffix:
          - -cuda
        include:
          - rosdistro: humble
            container: ghcr.io/autowarefoundation/autoware:latest-prebuilt
            build-depends-repos: build_depends.repos
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Show disk space before the tasks
        run: df -h

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get self packages
        id: get-self-packages
        uses: autowarefoundation/autoware-github-actions/get-self-packages@v1

      - name: Create ccache directory
        run: |
          mkdir -p ${CCACHE_DIR}
          du -sh ${CCACHE_DIR} && ccache -s
        shell: bash

      - name: Attempt to restore ccache
        if: matrix.container-suffix == '-cuda'
        uses: actions/cache/restore@v4
        with:
          path: |
            /root/.ccache
          key: ccache-main-${{ runner.arch }}-${{ matrix.rosdistro }}-${{ github.sha }}
          restore-keys: |
            ccache-main-${{ runner.arch }}-${{ matrix.rosdistro }}-

      - name: Show ccache stats before build
        run: du -sh ${CCACHE_DIR} && ccache -s
        shell: bash

      # TODO: before merging, keep target-packages unchanged
      - name: Build
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-build@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: imu_corrector
          build-depends-repos: ${{ matrix.build-depends-repos }}

      - name: Show ccache stats after build
        run: du -sh ${CCACHE_DIR} && ccache -s
        shell: bash

      # TODO: before merging, only run on push to main
      - name: Push the ccache cache
        if: matrix.container-suffix == '-cuda'
        uses: actions/cache/save@v4
        with:
          path: |
            /root/.ccache
          key: ccache-main-${{ runner.arch }}-${{ matrix.rosdistro }}-${{ github.sha }}

      #      - name: Test
      #        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
      #        id: test
      #        uses: autowarefoundation/autoware-github-actions/colcon-test@v1
      #        with:
      #          rosdistro: ${{ matrix.rosdistro }}
      #          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
      #          build-depends-repos: ${{ matrix.build-depends-repos }}
      #
      #      - name: Upload coverage to CodeCov
      #        if: ${{ steps.test.outputs.coverage-report-files != '' }}
      #        uses: codecov/codecov-action@v4
      #        with:
      #          files: ${{ steps.test.outputs.coverage-report-files }}
      #          fail_ci_if_error: false
      #          verbose: true
      #          flags: total

      - name: Show disk space after the tasks
        run: df -h
